# Transforming Numerical Variables
- če značilke niso normalno distribuirane, uporabljamo različne transformacije, da spremenimo distribucije
- na ta način izboljšamo performanco linearnih ML problemov
- lahko rečemo da lineariziramo prostor značilk


In [2]:
import numpy as np
import pandas as pd

%matplotlib inline
import matplotlib.pyplot as plt
import scipy.stats as stats

## Transforming variables with the logarithm
- strong effect on the shape of the variable distribution and can only be applied to positive variables
- pri Function transformerjih ni fit koraka, saj ne fittamo ampak samo funkcijsko transformiramo podatke

In [ ]:
import scipy.stats as stats
from sklearn.datasets import load_boston
from sklearn.preprocessing import FunctionTransformer

In [ ]:
data = pd.read_csv("data/boston.csv")
data.head()

In [ ]:
def diagnostic_plots(df, variable):
    plt.figure(figsize=(12,4))
    plt.subplot(1, 2, 1)
    df[variable].hist(bins=30)
    plt.subplot(1, 2, 2)
    stats.probplot(df[variable], dist="norm", plot=plt)
    plt.show()

In [ ]:
diagnostic_plots(data, 'LSTAT')

# vidimo da podatki niso normalno porazdeljeni

In [ ]:
data_tf = data.copy()

In [ ]:
data_tf[['LSTAT', 'NOX', 'DIS', 'RM']] = np.log(data[['LSTAT', 'NOX', 'DIS', 'RM']])

In [ ]:
diagnostic_plots(data_tf, 'LSTAT')

In [ ]:
transformer = FunctionTransformer(np.log)

In [ ]:
data_tf = transformer.transform(data[['LSTAT', 'NOX', 'DIS', 'RM']])

## Transforming variables with the reciprocal function
- drastičen efekt na porazdelitev
- značilke ne smejo biti 0

In [ ]:
from sklearn.preprocessing import FunctionTransformer


data = pd.read_csv("data/boston.csv")

In [ ]:
def diagnostic_plots(df, variable):
    # function to plot a histogram and a Q-Q plot
    # side by side, for a certain variable
    plt.figure(figsize=(10,4))
    plt.subplot(1, 2, 1)
    df[variable].hist(bins=30)
    plt.subplot(1, 2, 2)
    stats.probplot(df[variable], dist="norm", plot=plt)
    plt.show()

In [ ]:
diagnostic_plots(data, 'DIS')

In [ ]:
transformer = FunctionTransformer(np.reciprocal)

In [ ]:
data_tf = transformer.transform(data[['LSTAT', 'NOX', 'DIS', 'RM']])

In [ ]:
data_tf = pd.DataFrame(data_tf, columns=['LSTAT', 'NOX', 'DIS', 'RM'])
diagnostic_plots(data_tf, 'DIS')

## Using power transformations on numerical variables

In [ ]:
from sklearn.preprocessing import FunctionTransformer

data = pd.read_csv("data/boston.csv")

In [ ]:
data.head()

In [ ]:
data.hist(bins=30, figsize=(10,10))
plt.show()

In [ ]:
diagnostic_plots(data, 'LSTAT')

In [ ]:
# make a copy of the dataframe where we will store the modified
# variables
data_tf = data.copy()

In [ ]:
transformer = FunctionTransformer(lambda x: np.power(x, 0.3))

# capture variables to transform in a list
cols = ['LSTAT', 'NOX', 'DIS', 'RM']

# transform slice of dataframe with indicated variables
data_tf = transformer.transform(data[cols])

data_tf = pd.DataFrame(data_tf, columns=cols)

In [ ]:
# visualize the transformation (not in book)
diagnostic_plots(data_tf, 'LSTAT')

## Using square and cube root to transform variables

In [ ]:
data = pd.read_csv("data/boston.csv")

data_tf = data.copy()

transformer = FunctionTransformer(np.sqrt)

# make a list of variables to transform
cols = ['LSTAT', 'NOX', 'DIS', 'RM']

# transform slice of dataframe with indicated variables
# returns NumPy array
data_tf = transformer.transform(data[cols])

data_tf = pd.DataFrame(data_tf, columns=cols)

In [ ]:
diagnostic_plots(data_tf, 'LSTAT')

## Example: Customer churn dataset

In [6]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix

In [7]:
df = pd.read_csv('data/sampleSubmission.csv')
df = df.rename(columns=str.lower)
df['churn'] = df['churn'].replace(('yes', 'no'), (1, 0))
df.head()

state  account_length      area_code international_plan voice_mail_plan  \
0    OH             107  area_code_415                 no             yes   
1    NJ             137  area_code_415                 no              no   
2    OH              84  area_code_408                yes              no   
3    OK              75  area_code_415                yes              no   
4    MA             121  area_code_510                 no             yes   

   number_vmail_messages  total_day_minutes  total_day_calls  \
0                     26              161.6              123   
1                      0              243.4              114   
2                      0              299.4               71   
3                      0              166.7              113   
4                     24              218.2               88   

   total_day_charge  total_eve_minutes  total_eve_calls  total_eve_charge  \
0             27.47              195.5              103             16.62   
1             41.38              121.2              110             10.30   
2             50.90               61.9               88              5.26   
3             28.34              148.3              122             12.61   
4             37.09              348.5              108             29.62   

   total_night_minutes  total_night_calls  total_night_charge  \
0                254.4                103               11.45   
1                162.6                104                7.32   
2                196.9                 89                8.86   
3                186.9                121                8.41   
4                212.6                118                9.57   

   total_intl_minutes  total_intl_calls  total_intl_charge  \
0                13.7                 3               3.70   
1                12.2                 5               3.29   
2                 6.6                 7               1.78   
3                10.1                 3               2.73   
4                 7.5                 7               2.03   

   number_customer_service_calls  churn  
0                              1      0  
1                              0      0  
2                              2      0  
3                              3      0  
4                              3      0

In [8]:
df.isnull().sum()

state                            0
account_length                   0
area_code                        0
international_plan               0
voice_mail_plan                  0
number_vmail_messages            0
total_day_minutes                0
total_day_calls                  0
total_day_charge                 0
total_eve_minutes                0
total_eve_calls                  0
total_eve_charge                 0
total_night_minutes              0
total_night_calls                0
total_night_charge               0
total_intl_minutes               0
total_intl_calls                 0
total_intl_charge                0
number_customer_service_calls    0
churn                            0
dtype: int64

In [9]:
df.shape

(4250, 20)

In [10]:
X = df.drop(['churn'], axis=1)
y = df['churn']

### Simple baseline

In [11]:
def get_score(model, X_train, X_test, y_train, y_test):
    predictions = model.predict(X_test)
    print(f"------------- {type(model).__name__} -------------")
    print(f"Training set score: {model.score(X_train, y_train):.2f}")
    print(f"Test set score: {model.score(X_test, y_test):.2f}")
    print('Accuracy: ', accuracy_score(y_test, predictions))
    print(confusion_matrix(y_test, predictions))

In [12]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

X = pd.get_dummies(X) # narobe -> encoding moramo narediti ko razdelimo na train in test

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

knn = KNeighborsClassifier(n_neighbors=8)
knn.fit(X_train, y_train)
get_score(knn, X_train, X_test, y_train, y_test)

log = LogisticRegression(max_iter=10000)
log.fit(X_train, y_train)
get_score(log, X_train, X_test, y_train, y_test)

tree = DecisionTreeClassifier(max_depth=10)
tree.fit(X_train, y_train)
get_score(tree, X_train, X_test, y_train, y_test)

------------- KNeighborsClassifier -------------
Training set score: 0.90
Test set score: 0.89
Accuracy:  0.8941176470588236
[[1096    6]
 [ 129   44]]
------------- LogisticRegression -------------
Training set score: 0.87
Test set score: 0.87
Accuracy:  0.8705882352941177
[[1071   31]
 [ 134   39]]
------------- DecisionTreeClassifier -------------
Training set score: 0.98
Test set score: 0.94
Accuracy:  0.9403921568627451
[[1073   29]
 [  47  126]]


### With feature engineering
- iz vecih znacilk ustvarimo neko novo kombinirano znacilko


In [16]:
df = pd.read_csv('data/sampleSubmission.csv')
df = df.rename(columns=str.lower)
df['churn'] = df['churn'].replace(('yes', 'no'), (1, 0))
X = df.drop(['churn'], axis=1)
y = df['churn']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [26]:
df

state  account_length      area_code international_plan voice_mail_plan  \
0       OH             107  area_code_415                 no             yes   
1       NJ             137  area_code_415                 no              no   
2       OH              84  area_code_408                yes              no   
3       OK              75  area_code_415                yes              no   
4       MA             121  area_code_510                 no             yes   
...    ...             ...            ...                ...             ...   
4245    MT              83  area_code_415                 no              no   
4246    WV              73  area_code_408                 no              no   
4247    NC              75  area_code_408                 no              no   
4248    HI              50  area_code_408                 no             yes   
4249    VT              86  area_code_415                 no             yes   

      number_vmail_messages  total_day_minutes  total_day_calls  \
0                        26              161.6              123   
1                         0              243.4              114   
2                         0              299.4               71   
3                         0              166.7              113   
4                        24              218.2               88   
...                     ...                ...              ...   
4245                      0              188.3               70   
4246                      0              177.9               89   
4247                      0              170.7              101   
4248                     40              235.7              127   
4249                     34              129.4              102   

      total_day_charge  total_eve_minutes  total_eve_calls  total_eve_charge  \
0                27.47              195.5              103             16.62   
1                41.38              121.2              110             10.30   
2                50.90               61.9               88              5.26   
3                28.34              148.3              122             12.61   
4                37.09              348.5              108             29.62   
...                ...                ...              ...               ...   
4245             32.01              243.8               88             20.72   
4246             30.24              131.2               82             11.15   
4247             29.02              193.1              126             16.41   
4248             40.07              223.0              126             18.96   
4249             22.00              267.1              104             22.70   

      total_night_minutes  total_night_calls  total_night_charge  \
0                   254.4                103               11.45   
1                   162.6                104                7.32   
2                   196.9                 89                8.86   
3                   186.9                121                8.41   
4                   212.6                118                9.57   
...                   ...                ...                 ...   
4245                213.7                 79                9.62   
4246                186.2                 89                8.38   
4247                129.1                104                5.81   
4248                297.5                116               13.39   
4249                154.8                100                6.97   

      total_intl_minutes  total_intl_calls  total_intl_charge  \
0                   13.7                 3               3.70   
1                   12.2                 5               3.29   
2                    6.6                 7               1.78   
3                   10.1                 3               2.73   
4                    7.5                 7               2.03   
...                  ...               ...                ...   
4245  

In [17]:
def get_total_net_minutes(df):
    df['total_net_minutes'] = df['total_day_minutes'] + df['total_eve_minutes'] + df['total_night_minutes']
    return df

def get_total_net_calls(df):
    df['total_net_calls'] = df['total_day_calls'] + df['total_eve_calls'] + df['total_night_calls']
    return df

def get_total_net_charge(df):
    df['total_net_charge'] = df['total_day_charge'] + df['total_eve_charge'] + df['total_night_charge']
    return df

def cs_calls_per_month(df):
    df['cs_calls_per_month'] = (df['number_customer_service_calls'] + df['number_vmail_messages']) / df['account_length']
    return df

In [19]:
feature_engineering = ColumnTransformer([
    ('total_net_minutes', FunctionTransformer(get_total_net_minutes, validate=False),['total_day_minutes', 'total_eve_minutes', 'total_night_minutes']),
    ('total_net_calls', FunctionTransformer(get_total_net_calls, validate=False),['total_day_calls', 'total_eve_calls', 'total_night_calls']),
    ('total_net_charge', FunctionTransformer(get_total_net_charge, validate=False),['total_day_charge', 'total_eve_charge', 'total_night_charge']),
    ('cs_calls_per_month', FunctionTransformer(cs_calls_per_month, validate=False),['account_length', 'number_customer_service_calls', 'number_vmail_messages']),
])

In [20]:
categorical_columns = list(X_train.select_dtypes(include=['object']).columns.values.tolist())
numeric_columns = list(X_train.select_dtypes(exclude=['object']).columns.values.tolist())

In [21]:
numeric_transformer = SimpleImputer(strategy='constant')

categorical_transformer = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
        ('onehot', OneHotEncoder(handle_unknown='ignore')),
    ])

In [22]:
preprocessor = ColumnTransformer(
    transformers=[
        ('feature_engineering', feature_engineering, numeric_columns), # izvedemo zgoraj definiran ColumnTransformer za numericne znacilke
        ('numeric_transformers', numeric_transformer, numeric_columns),
        ('categorical_transformers', categorical_transformer, categorical_columns),
    ])

In [23]:
model = DecisionTreeClassifier(max_depth=10)

pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                           ('model', model)])

In [24]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('feature_engineering',
                                                  ColumnTransformer(transformers=[('total_net_minutes',
                                                                                   FunctionTransformer(func=<function get_total_net_minutes at 0x0000015829C2D9E0>),
                                                                                   ['total_day_minutes',
                                                                                    'total_eve_minutes',
                                                                                    'total_night_minutes']),
                                                                                  ('total_net_calls',
                                                                                   FunctionTransformer(func=<function get_total_net_...
                                                   'total_intl_calls',
                                                   'total_intl_charge',
                                                   'number_customer_service_calls']),
                                                 ('categorical_transformers',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['state', 'area_code',
                                                   'international_plan',
                                                   'voice_mail_plan'])])),
                ('model', DecisionTreeClassifier(max_depth=10))])

In [25]:
get_score(pipeline, X_train, X_test, y_train, y_test)

------------- Pipeline -------------
Training set score: 0.98
Test set score: 0.97
Accuracy:  0.971764705882353
[[1095    7]
 [  29  144]]
